apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fzqihw024-nodejs-gitops
  description: This is GitOps manifest for fzqihw024-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=fzqihw024-nodejs
    backstage.io/kubernetes-id: fzqihw024-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fzqihw024-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fzqihw024-nodejs
